---
title:"AI"
author: "Dongdong Kong"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
source("scripts/main_pkgs.R")
library(sf)
library(sf2)
library(lattice.layers)

sp_cont <- list("sp.lines", get_continent(), lwd = 0.2, first = F)
sp_layout <- list(sp_cont)
# sp_sign = list("sp.polygons", poly_shade, first = FALSE, lwd = 0.1)
load(file = "data-raw/Multimodel mean E Trends from CIMP6 and GLEAM.RData")
AI <- raster("INPUTS/AridityIndex_MSWEP-prcp_div_GLEAM-Ep_1980-2020.tif") %>%
  raster2array() %>%
  as.numeric()
```

# Figure S1:

准备数据：
```{r}
library(rgdal)
library(lattice.layers)
library(rcolors)
library(sf)

sp_cont <- list("sp.lines", get_continent(), lwd = 0.5, first = F)
sp_layout <- list(sp_cont)

brks <- c(-Inf, 0.2, 0.5, 0.65, Inf)
levs <- c("arid", "semi-arid", "sub-humid", "humid")

g <- readGDAL("INPUTS/AridityIndex_MSWEP-prcp_div_GLEAM-Ep_1980-2020.tif")
g$band1 %<>% clamp(c(0, 10), TRUE) #%>% cut(brks)
```

出图：
```{r}
# brks = c(-Inf, 0, 0.05, 0.2, 0.5, 0.65, Inf)
# brks2 = c(0.05, 0.2, 0.5, 0.65, 1, 2, 5)
brks2 = c(0.05, 0.2, 0.65, 1)
brks <- c(-Inf, 0, 0.05, 0.2, 0.5, 0.65, 1:5, 20, Inf)

nbrk = length(brks) - 1
n_more = 2
cols <- get_color(rcolors$amwg256, nbrk+n_more) %>% .[-(1:n_more)] %>% rev()
p <- sp_plot(g,
              brks = brks,
              cols = cols,
              xlim = c(-180, 240),
              ylim = c(-60, 90),
              aspect = 0.5,
              sp.layout = sp_layout,
              key.num2factor = TRUE) +
    layer_title(x = 0, y = 1, labels = c("AI = P/PET")) +
    layer_latFreq(bbox = c(185, 240, -60, 90), zlim = c(-2, 2),
                  col.regions = NULL, 
                  unit = "native", is_spatial =TRUE) +
    layer_barchart(x = 0.01, y = 0.05, width = 0.22) +
    layer_contourf(at = brks2, col = "black")
    # layer_statistic(x = 0.4, y = 0.1, cex = 1.4)
write_fig(p, "Figure_S01_AridityIndex_SpatialDistribution2.pdf", 10.7, 5)
```
